apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:3.5.1
          command: ["/opt/spark/bin/spark-class"]
          args:
            - org.apache.spark.deploy.master.Master
            - --host
            - spark-master
            - --port
            - "7077"
            - --webui-port
            - "8080"
          ports:
            - containerPort: 7077
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: spark
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
  type: ClusterIP
