apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: spark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: apache/spark:3.5.1
          command: ["/opt/spark/bin/spark-class"]
          args:
            - org.apache.spark.deploy.worker.Worker
            - --webui-port
            - "8081"
            - spark://spark-master:7077
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: spark
spec:
  selector:
    app: spark
    role: worker
  ports:
    - name: webui
      port: 8081
      targetPort: 8081
  type: ClusterIP
