apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_HOST
              value: 0.0.0.0
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_PUBLIC_DNS
              value: spark-master
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 7077
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: spark
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
  type: NodePort
